vich_uploader:
    db_driver: orm
    mappings:
        user_profile_pictures:
            uri_prefix: '%app.path.user_profile_pictures%'
            upload_destination: '%kernel.project_dir%/public/%app.path.user_profile_pictures%'
