vich_uploader:
    db_driver: orm
    mappings:
        user_profile_pictures:
            uri_prefix: /uploads/user_profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/user_profile_pictures'
